### ISSUE TITLE
Clear identifier of an agent in the Assistant Manifest

### ISSUE THREAD

**Issue by schnelle** [open-voice-interoperability/docs#4]
The [Assistant Manifiest](https://github.com/open-voice-interoperability/docs/blob/main/specifications/AssistantManifest/0.9.0/AssistantManifestSpec.md) lists several features under identification but none of them seems to be suited to uniquely identify an agent.

This might be useful in case you want to refer to a specific agent, e.g. when resuming the conversation with exactly that agent.

**Comment by davidattwater** [comment]
The spec intends the URL to be a unique ID of a personified agent.  
The document should be amended to make this clear. 

The conversational envelope spec needs to resolve the distinction between speaker IDs and URLs of agents/conversants.

**Comment by davidattwater** [comment]
Done in manifest 0.9.1
