### ISSUE TITLE
supportedLayers in the Assistant Manifest should separate in and out

### ISSUE THREAD

**Issue by schnelle** [open-voice-interoperability/docs#5]
The [Assistant Manifest](https://github.com/open-voice-interoperability/docs/blob/main/specifications/AssistantManifest/0.9.0/AssistantManifestSpec.md) suggests to use supportedLayers to specify how the agent can interact with others. I would perceive this as modality.

Actually, the abilities of agents may differ in this regard. Imagine an agent that receives text input to generate images. I was not able to find this separation in the current specification.

**Comment by davidattwater** [comment]
"supportedLayers": {
                    "input" : [ 
                        "text"
                    ],
                    "output" : [
                        "text"
                    ]
                }

**Comment by davidattwater** [comment]
Done in 0.9.1
