### ISSUE TITLE
authentication as part of the Assistant Manifest

### ISSUE THREAD

**Issue by schnelle** [open-voice-interoperability/docs#6]
The [Assisten Manifest](https://github.com/open-voice-interoperability/docs/blob/main/specifications/AssistantManifest/0.9.0/AssistantManifestSpec.md) does not mention anything about authentication of users.

Authentication is not only needed to know who the user is and if she is allowed to use the service provided by the assistant. Moreover, it is possible that the service an agent offers depend on subsrcriptions and may differ for different users,

**Comment by davidattwater** [comment]
Add this to the issues log in the spec.

**Comment by davidattwater** [comment]
Done in 0.9.1
