### ISSUE TITLE
Role of "role" not clear in Assistant Manifest

### ISSUE THREAD

**Issue by schnelle** [open-voice-interoperability/docs#8]
Reading the [Assistant Manifes](https://github.com/open-voice-interoperability/docs/blob/main/specifications/AssistantManifest/0.9.0/AssistantManifestSpec.md)t, it did not become clear to me under which conditions the role of the identifaction is used,

**Comment by davidattwater** [comment]
Add a note onto 'synopsis' that this is a redundant field that summarizes the org/department/role of the agent

**Comment by schnelle** [comment]
I was expecting to find this in the table in section 1.6  of the [Assistant Manifest 0.9.1](https://github.com/open-voice-interoperability/docs/blob/main/specifications/AssistantManifest/0.9.1/AssistantManifestSpec.md) but was not able to spot it there. Am I missing something?

**Comment by davidattwater** [comment]
Yes. I thought I had done this but when I look you are right it does not meet the needs of this issue. I have re-written it as follows: 

A sentence summarizing who the assistant is and their area of expertise. This sentence is intended to be spoken to the user and should take less than five seconds to verbalize. In English this would typically be less than 75 characters. **This is a natural language synopsis of the contents of the whole manifest and should not contain new information that is not present in the specific fields of the manifest.**

**Comment by schnelle** [comment]
Looks good to me now. Thank you
