### ISSUE TITLE
Role of "serviceName" not clear in Assistant Manifest

### ISSUE THREAD

**Issue by schnelle** [open-voice-interoperability/docs#9]
In the [Assistant Manifest](https://github.com/open-voice-interoperability/docs/blob/main/specifications/AssistantManifest/0.9.0/AssistantManifestSpec.md) it did not become clear to me under which conditions the serviceName is used and what it is expected to add to conversationalName and synopsis.

**Comment by davidattwater** [comment]
It was agreed to rename this as 'department'

**Comment by davidattwater** [comment]
Added to spec 0.9.1
